### ISSUE TITLE
 rehype-prism@1.0.1 is not available in npmjs

### ISSUE THREAD

**Issue by evomac** [Val-istar-Guo/rehype-prism#7]
**Describe the bug**
When I'm trying to install rehype-prism it says a package version that doesn't exist

**To Reproduce**
1. Go to Terminal
2. Open project
4. Write npm install rehype-prism@1.0.1
5. See error6. 

`❯ npm install rehype-prism@1.0.1
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: rehype-prism@1.0.1
npm WARN Found: unified@9.2.0
npm WARN node_modules/unified
npm WARN   unified@"9.2.0" from @mdx-js/mdx@1.6.22
npm WARN   node_modules/@mdx-js/mdx
npm WARN     @mdx-js/mdx@"^1.6.22" from @web/dev-server-storybook@0.3.7-next.0
npm WARN     node_modules/@web/dev-server-storybook
npm WARN     1 more (storybook-addon-markdown-docs)
npm WARN   1 more (remark-mdx)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer unified@"^9 | ^10" from rehype-prism@1.0.1
npm WARN node_modules/rehype-prism
npm WARN   rehype-prism@"1.0.1" from the root project
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: rehype-prism@1.0.1
npm WARN Found: unified@undefined
npm WARN node_modules/unified
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer unified@"^9 | ^10" from rehype-prism@1.0.1
npm WARN node_modules/rehype-prism
npm WARN   rehype-prism@"1.0.1" from the root project
npm ERR! code ETARGET
npm ERR! notarget No matching version found for unified@^9 | ^10.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
`

**Expected behavior**
Correctly published pack and build package.json file

**Platform (please complete the following information):**
 - Device: Windows, Mac
 - OS: Windows 11, Mac OS Monterey, Big Sur
 - Environment: Nodejs v16, npm 8.3.1, npm 8.5.3
 - Version 1.0.1

**Comment by msw119822** [comment]
We are also having. We are having to pin rehype-prism to version 1.0.0 for this to work

**Comment by Val-istar-Guo** [comment]
what a stupid mistake . -_-||

**Comment by Val-istar-Guo** [comment]
A new version has been released, upgrade to 1.0.2 and try again.

**Comment by Val-istar-Guo** [comment]
Many similar plug-ins choose to use [refractor](https://www.npmjs.com/package/refractor). [refractor](https://www.npmjs.com/package/refractor) also depends on prismjs. Should we use it?

**Comment by msw119822** [comment]
The issue is corrected for my team. Thank you.
